apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stringservice
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: stringservice
    spec:
      containers:
      - name: stringservice
        image: valeriogheri/stringservice:latest
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command:
        - "/bin/sh"
        - "-c"
        - "HTTP_PROXY=$(NODE_NAME):4140 ./stringservice"
        ports:
        - containerPort: 1337
        imagePullPolicy: IfNotPresent
      - name: kubectl
        image: buoyantio/kubectl:v1.4.0
        args:
        - proxy
        - "-p"
        - "8001"
