apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-config
data:
  config.yaml: |-
    admin:
      port: 9990

    namers:
    - kind: io.l5d.k8s
      experimental: true
      host: 127.0.0.1
      port: 8001

    routers:
    - protocol: http
      servers:
      - port: 8080
        ip: 0.0.0.0
      baseDtab: |
        /iface      => /#/io.l5d.k8s/default;
        /srv        => /iface/http;
        /http/1.1/* => /srv;
